name: Jake Moreman
url: "http://jakemoreman.co.uk"

markdown: rdiscount
rdiscount:
  extensions: [smart]
  
pygments: true
permalink: /:year/:month/:day/:title
exclude: ['Gemfile*', 'README.md']

prose:
  siteurl: "http://jakemoreman.co.uk"
    
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
          
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: 'http://jakemoreman.co.uk/resources/tags.jsonp'
          alterable: true
